### ISSUE TITLE
Running in console

### ISSUE THREAD

**Issue by TkTzLabs** [Shemka/cryptoTrader#1]
Hello I am running trader.py from console by adding in the end of file following:

`strategy = BacktestStrategy('data/train_440d.csv')
backtesting = Backtest('data/test_2M.csv', strategy)
backtesting.testing()
`
and commenting out `init_notebook_mode(connected=True)`

I can see the increase of CPU activity and also lot of memory is loaded but no result or no progress at all -> seeying just:
`Using Numpy backend.
----- ESN_Price_Predictor_Base_v0.1 -----
Start balance: 0.0048
100% (631186 of 631186) |################| Elapsed Time: 0:02:28 Time:  0:02:28
init_dgesdd failed init
Model ready for work!
Profit:0.0% 
Profit amount:0.0 BTC 
Start balance:0.0048 BTC 
End balance:0.0048 BTC
`

Do you know what went wrong ?

**Comment by Shemka** [comment]
I'm sorry, but this project is frozen for now due to his not effectivity. All files i provide is just a pre-alpha with a lot of bugs (or features :))
